version: "3.0"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always
    networks:
      - mern-app

  server:
    container_name: bugzilla_server
    image: bugzilla_server:0.0.1
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - /server/node_modules

    ports:
      - 8000:8000
    restart: always
    depends_on:
      - mongo-express
    networks:
      - mern-app

  client:
    container_name: bugzilla_client
    image: bugzilla_client:0.0.1
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules

    ports:
      - 3000:3000
    restart: always
    depends_on:
      - server
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local



